In [4]:
#Numpy 
#it is a library in python which is used for scientific computing and data analysis. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.
!pip install numpy


  Using cached numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 6.6 MB/s  0:00:02a 0:00:01m eta 0:00:01


In [14]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(arr.shape)

arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.shape)

arr2d.reshape(3,2)
print(arr2d)

np.arange(0,10,3) #start, stop, step
print(np.arange(0,10,3))

np.ones((2,3)) #array of ones with shape (2,3)
print(np.ones((2,3)))

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]
[0 3 6 9]
[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#vectorise operations
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2) #element wise addition
print(arr1 * arr2) #element wise multiplication

#some useful functions
print(np.sum(arr1)) #sum of all elements
print(np.mean(arr1)) #mean of all elements
print(np.std(arr1)) #standard deviation of all elements
print(np.min(arr1)) #minimum element
print(np.max(arr1)) #maximum element


[5 7 9]
[ 4 10 18]
6
2.0
0.816496580927726
1
3


In [19]:
#indexing and slicing
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])

print(arr[0,0]) #first row, first column

#suppose i want 4,5,40,50
print(arr[0:2,3:5]) #first 2 rows, last 2 columns

1
[[ 4  5]
 [40 50]]


In [23]:
#logical indexing
print(arr[arr > 20]) #all elements greater than 20

#logical indexing with condition
print(arr[(arr > 20) & (arr < 50)]) #all elements greater than 20 and less than 50

#logvcal operations with broadcasting
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr + 10) #add 10 to all elements
print(arr * 2) #multiply all elements by 2

arr > 5 #logical operation with broadcasting, returns a boolean array


[]
[]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])